container:
  image: node:latest
  cpu: 8
  memory: 10G

test_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  reanme_script: npm run start