container:
  image: node:16.x
  cpu: 8
  memory: 10G

testServer_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  testServer_script: npm run start